// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw9JoMl5b0rh6KwxWBgpmDErjKFhUxwbM',
    appId: '1:555542404282:web:f92935023bcfe7c2fa7683',
    messagingSenderId: '555542404282',
    projectId: 'laza-67c82',
    authDomain: 'laza-67c82.firebaseapp.com',
    storageBucket: 'laza-67c82.appspot.com',
    measurementId: 'G-QC3PM14VY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76vPFVEsGiz3-YjzQerig8Y2tdce1aXE',
    appId: '1:555542404282:android:fbe1596699ffa98efa7683',
    messagingSenderId: '555542404282',
    projectId: 'laza-67c82',
    storageBucket: 'laza-67c82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7xSknXsQBDAny-4L2lxHreGcA47WuEo',
    appId: '1:555542404282:ios:4f7007d6f7813afdfa7683',
    messagingSenderId: '555542404282',
    projectId: 'laza-67c82',
    storageBucket: 'laza-67c82.appspot.com',
    iosClientId: '555542404282-po5l7fs5knse1uuesaeicpavsh5bivvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7xSknXsQBDAny-4L2lxHreGcA47WuEo',
    appId: '1:555542404282:ios:08f9d5401bfe4e25fa7683',
    messagingSenderId: '555542404282',
    projectId: 'laza-67c82',
    storageBucket: 'laza-67c82.appspot.com',
    iosClientId: '555542404282-bdo6fm3o5bnhj7gpgi2fbtoj0q0h3cde.apps.googleusercontent.com',
    iosBundleId: 'com.example.laza.RunnerTests',
  );
}
